---

# Ansible and host configuration
ansible_user: vagrant
ansible_connection: local

# Custom ansible
ansible_retries: 5
ansible_delay: 1

# User
user:
    name: vagrant
    password: vagrant
    group: users
    shell: /bin/zsh
    folders:
    - private/projects
    - work/projects
    dotfiles: https://github.com/badele/dotfiles.git

packages:
  install:
  # Base
  - base-devel
  - wget
  - curl
  - git
  - yay
  - rsync
  - neofetch
  - pulseaudio
  - pulseaudio-alsa
  # Shell
  - zsh
  - fd
  - fzf
  - navi
  - ripgrep
  - autojump
  # Performances tools
  - lsof
  - ltrace
  - strace
  - sysstat
  - nmap
  # Editor
  - neovim
  # tools
  - ranger
  remove:
#  - cloud-init

system:
    locale:
    - fr_FR.UTF-8
    - en_US.UTF-8
    timezone: Europe/Paris
    keyboard: fr

    # mkinitcpio ( https://wiki.archlinux.org/index.php/mkinitcpio#BINARIES_and_FILES )
    kernel_binaries: "btrfsck"
    kernel_hooks: "base udev autodetect keyboard keymap consolefont modconf block encrypt lvm2 filesystems fsck btrfs"

    # mkinitcpio ( https://wiki.archlinux.org/index.php/mkinitcpio#BINARIES_and_FILES )
    kernel_binaries: "btrfsck"
    kernel_hooks: "base udev autodetect keyboard keymap consolefont modconf block encrypt lvm2 filesystems fsck btrfs"
