- name: backlight | Set udev backlight permission
  become: true
  copy:
    dest: /etc/udev/rules.d/backlight.rules
    content: |
      RUN+="/bin/chgrp video /sys/class/backlight/amdgpu_bl0/brightness"
      RUN+="/bin/chmod g+w /sys/class/backlight/amdgpu_bl0/brightness"