---

- name: btrfs | install packages
  aur:
    use: yay
    name:
    - btrfs-progs
    - grub-btrfs
    - snapper
    - snap-pac

  register: task_result
  until: task_result is success
  retries: "{{ ansible_retries }}"
  delay: "{{ ansible_delay }}"

- name: btrfs | check snapper config exists
  become: true
  stat:
    path: /etc/snapper/configs/root
  register: snapperconfig

- name: btrfs | create snapper config
  command: "snapper -c root create-config /"
  become: true
  when: not snapperconfig.stat.exists

- name: btrfs | snap-pac configuration
  become: true
  copy:
    src: snappac.conf
    dest: /etc/snap-pac/root.conf