---

- name: i3 | Install i3 packages
  aur:
    use: yay
    name:
    # Xorg
    - xorg
    - xorg-xinit
    - xf86-input-synaptics
    - xterm
    - polkit-gnome
    - network-manager-applet
    - xautolock
    - dunst
    - libnotify
    - picom
    # Terminal
    - termite
    # i3
    - i3-gaps
    - i3lock
    - xtrlock
    - i3exit
    - i3-scrot
    - feh
    - gpick
    - polybar
    - rofi
    - papirus-icon-theme
    - autorandr
    # Themes
    - termpalette-git
    - wpgtk-git
    - colorz
    # Misc
    - playerctl

  register: task_result
  until: task_result is success
  retries: "{{ ansible_retries }}"
  delay: "{{ ansible_delay }}"
  when: packages.install is defined

- name: i3 | set xorg keyboard
  become: true
  command: "localectl set-x11-keymap --no-convert {{ system.keyboard }}"

# Execute only if /home/{{ user.name }}/.config/i3/config file not exists
#- name: i3 | init some config files from wpg template
#  command: /home/{{ user.name }}/.local/bin/set-color-scheme-from-image creates=/home/{{ user.name }}/.config/i3/config
