---
# https://github.com/kostajh/taskwarrior-time-tracking-hook
- name: tw | Install tw packages
  aur:
    use: yay
    name:
    - task
    - taskwarrior-tui

  register: task_result
  until: task_result is success
  retries: "{{ ansible_retries }}"
  delay: "{{ ansible_delay }}"
  

- name: tw | Install taskwarrior-time-tracking-hook
  pip:
    name: taskwarrior-time-tracking-hook